from schemas.authConfiguration import authConfiguration
from schemas.airlineSchema import airlineSchema, validate_airlineSchema
from schemas.airportSchema import airportSchema
from schemas.aircraftSchema import aircraftModelSchema, aircraftPartSchema, aircraftSchema
from schemas.airbusSchema import sellAircraftSchema
from schemas.skillSchema import skillSchema
