from routers import auth
from routers.generative_ai import generative_ai
from routers.segmentation_object_detection import segmentation_object_detection
from routers.airline import airline
from routers.airport import airport
from routers.aircraft import aircraft
from routers.skill import skill
from routers.airbus import airbus
from routers.pilot import pilot
